name: Generate a list of contributors

on:
  push:
    branches:
      - main

jobs:
  generate-contributors-list:
    runs-on: ubuntu-latest
    steps:
      - name: Contributors list
        uses: akhilmhdh/contributors-readme-action@v2.3.6
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
