name: Generate a list of contributors

on:
  push:
    branches:
      - main

jobs:
  generate-contributors-list:
    runs-on: ubuntu-latest
    steps:
      - name: Contributors list
        uses: akhilmhdh/contributors-readme-action@v2.3.6
        with:
          image_size: 60
          columns_per_row: 8
          use_username: true
          readme_path:
            - "./docs/1.md"
            - "./docs/2.md"
            - "README.md"
          commit_message: "docs(contributor): generate a list of contributors"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
